title: New page Generator
author: MilevaM 
email: mileva_225@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
---
title: "Accountants today"
date: 2018-09-10
---

# social links
twitter_username: your-twitter-handle
github_username:  MilevaM

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
