title: New page Generator
author: MilevaM 
email: mileva_225@yahoo.com
description: > # this means to ignore newlines until "baseurl:"


# social links
twitter_username: your-twitter-handle
github_username:  MilevaM

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
